// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearData():Promise<void>;

export function Connect(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function ListPorts():Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function ReplayFile(arg1:string):Promise<void>;
